src/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('Order.urls')),
]

src/Order/urls.py
from django.urls import path

from .views import (HomeView, 
                    checkout,
                    ProductDetailView,
                    add_to_cart,
                    remove_from_cart
                    )

urlpatterns = [
    # Add your URL patterns here
    path('', HomeView.as_view(), name='home_page'),
    path('checkout/', checkout, name='checkout'),
    path('product/<slug:slug>/',ProductDetailView.as_view(), name='product'),
    path('add_to_cart/<slug:slug>/', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<slug:slug>/', remove_from_cart, name='remove_from_cart'),
]

src/Order/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.

CATERGORY_CHOICES = (
    ('S', 'Shirt'),   #(value in database, value displayed )
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATERGORY_CHOICES, max_length=2, default='S')
    label = models.CharField(choices=LABEL_CHOICES, max_length=1,default='P')
    slug = models.SlugField(unique = True,blank=True)
    description = models.TextField(default='A Shirt')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("product", kwargs = {
            'slug': self.slug
        })
    
    def add_to_cart_url(self):
        return reverse("add_to_cart", kwargs = {
            'slug': self.slug
        })
    
    def remove_from_cart_url(self):
        return reverse('remove_from_cart', kwargs = {
            'slug': self.slug
        })

class OrderItems(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItems)
    start_date = models.DateField(auto_now_add = True)
    ordered_date = models.DateField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    

src/Order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.views.generic import ListView, DetailView
from django.utils import timezone

from .models import Item, OrderItems, Order
# Create your views here.

class HomeView(ListView):
    model = Item
    paginate_by = 10
    template_name = "home_page.html"

class ProductDetailView(DetailView):
    model = Item
    template_name = "product.html"

def add_to_cart(request, slug):
    # Fetch the item using the provided slug, 404 if not found
    item = get_object_or_404(Item, slug=slug)
    
    # Query for an active order for the current user
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    
    # Check if an active order exists
    if order_qs.exists():
        # Get the first order from the queryset
        order = order_qs[0]
        
        # Check if the item is already in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = order.items.get(item__slug=item.slug)
            order_item.quantity += 1
            order_item.save()
        else:
            order_item = OrderItems.objects.create(user=request.user, item=item)
            order.items.add(order_item)
    else:
        # Adds an ordered date for the order
        ordered_date = timezone.now()
        
        # If no active order, create a new order
        order = Order.objects.create(
            user=request.user,
            ordered_date=ordered_date,
        )
        
        # Add the new order item to the order
        order_item = OrderItems.objects.create(user=request.user, item=item)
        order.items.add(order_item)
    
    # Correct redirect
    return redirect('product', slug=slug)

def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user = request.user,
        ordered=False
    )

    # Check if an active order exists
    if order_qs.exists():
        order = order_qs[0]
        # Check if the item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItems.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]

            order.items.remove(order_item)
            order_item.delete()
        else:
            # Add a message saying the order doesn't contain the item
            messages.info(request, "This item was not in your cart")
    else:
        # Add a message saying the user doesn't have an order
        messages.info(request, "You do not have an active order")

    return redirect("product", slug=slug)


def checkout(request):
    return render(request, 'checkout_page.html')

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} Document {% endblock title %} </title>
        <!-- MDB icon -->
        <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
        <!-- Font Awesome -->
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        />
        <!-- Google Fonts Roboto -->
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
        />
        <!-- MDB -->
        <link rel="stylesheet" href="{% static 'vendors/mdb.min.css' %}" />

    {% block styles %}

    {% endblock styles %}
</head>
<body>
    {% include 'navbar.html' %}

    {% include 'base/message.html' %}

    <!-- Start your project here-->
    {% block content %} 

    {% endblock content %}
    <!-- End your project here-->


    {% block scripts %} 
        <!-- MDB -->
        <script type="text/javascript" src="{% static 'vendors/mdb.umd.min.js' %}"></script>
        <!-- Custom scripts -->
        <script type="text/javascript"></script>
    {% endblock scripts %}
    
</body>
</html>

src/templates/base/message.html
<div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
</div>

src/templates/home_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock title %}

{% block styles %}
<style>
    .carousel-item {
        height: 50vh;
    }
    .card {
        box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
    }
    .footer-cta {
        box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 15px;
    }
    .price {
        color: #263238 !important;
        font-size: 24px !important;
    }
    .sale {
        color: #E53935 !important;
    }
    .card-title {
        color: #263238;
    }
    .sale-badge {
        background-color: #E53935;
    }
</style>
{% endblock styles %}


{% block content %}
    <!-- carousel
    <div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-mdb-ride="carousel">
    <div class="carousel-indicators">
        <button
        type="button"
        data-mdb-target="#carouselExampleCaptions"
        data-mdb-slide-to="0"
        class="active"
        aria-current="true"
        aria-label="Slide 1"
        ></button>
        <button
        type="button"
        data-mdb-target="#carouselExampleCaptions"
        data-mdb-slide-to="1"
        aria-label="Slide 2"
        ></button>
        <button
        type="button"
        data-mdb-target="#carouselExampleCaptions"
        data-mdb-slide-to="2"
        aria-label="Slide 3"
        ></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg" class="d-block w-100" alt="Wild Landscape"/>
        <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
        <div class="carousel-caption d-none d-sm-block mb-5">
            <h1 class="mb-4">
                    <strong>Learn Bootstrap 5 with MDB</strong>
                </h1>

                <p>
                    <strong>Best & free guide of responsive web design</strong>
                </p>

                <p class="mb-4 d-none d-md-block">
                    <strong>The most comprehensive tutorial for the Bootstrap 5. Loved by over 3 000 000 users. Video and written versions
                    available. Create your own, stunning website.</strong>
                </p>

                <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start free tutorial
                    <i class="fas fa-graduation-cap ms-2"></i>
                </a>
        </div>
        </div>
        <div class="carousel-item">
        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg" class="d-block w-100" alt="Camera"/>
        <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
        <div class="carousel-caption d-none d-md-block mb-5">
            <h1 class="mb-4">
                    <strong>Learn Bootstrap 5 with MDB</strong>
                </h1>

                <p>
                    <strong>Best & free guide of responsive web design</strong>
                </p>

                <p class="mb-4 d-none d-md-block">
                    <strong>The most comprehensive tutorial for the Bootstrap 5. Loved by over 3 000 000 users. Video and written versions
                    available. Create your own, stunning website.</strong>
                </p>

                <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start free tutorial
                    <i class="fas fa-graduation-cap ms-2"></i>
                </a>
        </div>
        </div>
        <div class="carousel-item">
        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg" class="d-block w-100" alt="Exotic Fruits"/>
        <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
        <div class="carousel-caption d-none d-md-block mb-5">
            <h1 class="mb-4">
                    <strong>Learn Bootstrap 5 with MDB</strong>
                </h1>

                <p>
                    <strong>Best & free guide of responsive web design</strong>
                </p>

                <p class="mb-4 d-none d-md-block">
                    <strong>The most comprehensive tutorial for the Bootstrap 5. Loved by over 3 000 000 users. Video and written versions
                    available. Create your own, stunning website.</strong>
                </p>

                <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start free tutorial
                    <i class="fas fa-graduation-cap ms-2"></i>
                </a>
        </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-mdb-target="#carouselExampleCaptions" data-mdb-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-mdb-target="#carouselExampleCaptions" data-mdb-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
    </div> -->

    <!--Main layout-->
    <main>
    <div class="container">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: #607D8B">
    <!-- Container wrapper -->
    <div class="container-fluid">

        <!-- Navbar brand -->
        <a class="navbar-brand" href="#">Categories:</a>

        <!-- Toggle button -->
        <button 
        class="navbar-toggler" 
        type="button" 
        data-mdb-toggle="collapse" 
        data-mdb-target="#navbarSupportedContent2" 
        aria-controls="navbarSupportedContent2" 
        aria-expanded="false" 
        aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent2">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <!-- Link -->
            <li class="nav-item acitve">
            <a class="nav-link text-white" href="#">All</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="#">Shirts</a>
                </li>
                <li class="nav-item">
                <a class="nav-link text-white" href="#">Sport wears</a>
                </li>
                <li class="nav-item">
                <a class="nav-link text-white" href="#">Outwears</a>
                </li>

        </ul>

        <!-- Search -->
        <form class="w-auto py-1" style="max-width: 12rem">
            <input type="search" class="form-control rounded-0" placeholder="Search" aria-label="Search">
        </form>

        </div>
    </div>
    <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->

    <!-- Products -->
    <section>
    <div class="text-center">
        <div class="row">
        
        {% for item in object_list %}
            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card">
                <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                    data-mdb-ripple-color="light">
                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                    class="w-100" />
                    <a href="{{ item.get_absolute_url }}">
                    <div class="mask">
                        <div class="d-flex justify-content-start align-items-end h-100">
                        <h5><span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span></h5>
                        </div>
                    </div>
                    <div class="hover-overlay">
                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                    </div>
                    </a>
                </div>
                <div class="card-body">
                    <a href="" class="text-reset">
                    <h5 class="card-title mb-2">{{item.title}}</h5>
                    </a>
                    <a href="{{ item.get_absolute_url }}" class="text-reset ">
                    <p>{{item.get_category_display}}</p>
                    </a>
                    {% if item.discount_price %}
                        <h6 class="mb-3" style="color: #263238; font-size: 24px;">
                            <s>${{ item.price }}</s>
                            <strong class="ms-2" style="color: #E53935;">${{ item.discount_price }}</strong>
                        </h6>
                    {% else %}
                        <h6 class="mb-3" style="color: #263238; font-size: 24px;">${{ item.price }}</h6>
                    {% endif %}
                    
                </div>
                </div>
            </div>
        {% endfor %}


        </div>
    </div>
    </section>

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
    <!-- Pagination -->  
    </div>
    </main>


    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); text-color: #E0E0E0">
        © 2022 Copyright:
        <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
    </footer>

{% endblock content %}

src/templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">DJe-commerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

src/templates/product.html
{% extends 'base.html' %}

{% block title %} Product {% endblock title %}

{% block content %}
    <!--Main layout-->
    <main class="mt-5 pt-4">
        <div class="container mt-5">
            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <div class="col-md-6 mb-4">
                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="" />
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-4">
                    <!--Content-->
                    <div class="p-4">
                        <div class="mb-3">
                            <a href="">
                                <span class="badge bg-dark me-1">{{object.get_category_display}}</span>
                            </a>
                            <a href="">
                                <span class="badge bg-info me-1">New</span>
                            </a>
                            <a href="">
                                <span class="badge bg-danger me-1">Bestseller</span>
                            </a>
                        </div>

                        <p class="lead">
                            {% if object.discount_price %}
                                <span class="me-1">
                                    <del>${{object.price}}</del>
                                </span>
                                <span>${{object.discount_price}}</span>
                            {% else %}
                                <span>${{object.price}}</span>
                            {% endif %}
                        </p>

                        <strong><p style="font-size: 20px;">Description</p></strong>

                        <p>{{object.description}}</p>

                        <!-- <form class="d-flex justify-content-left">
                            Default input
                            <div class="form-outline me-1" style="width: 100px;">
                                <input type="number" value="1" class="form-control" />
                            </div>
                            <button class="btn btn-primary ms-1" type="submit">
                                Add to cart
                                <i class="fas fa-shopping-cart ms-1"></i>
                            </button>
                        </form> -->
                        <a href="{{ object.add_to_cart_url }}" class="btn btn-primary ms-1" >
                            Add to cart
                            <i class="fas fa-shopping-cart ms-1"></i>
                        </a>
                        <a href="{{ object.remove_from_cart_url }}" class="btn btn-danger ms-1" >
                            Remove from cart
                            <i class="fas fa-shopping-cart ms-1"></i>
                        </a>
                        
                    </div>
                    <!--Content-->
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->

            <hr />

            <!--Grid row-->
            <div class="row d-flex justify-content-center">
                <!--Grid column-->
                <div class="col-md-6 text-center">
                    <h4 class="my-4 h4">Additional information</h4>

                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit voluptates, quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->

            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">
                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="" />
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">
                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="" />
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">
                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="" />
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->
        </div>
    </main>
    <!--Main layout-->

    <!-- footer -->
    <footer class="text-center text-white mt-4" style="background-color: #607d8b;">
        <!--Call to action-->
        <div class="pt-4 pb-2">
            <a class="btn btn-outline-white footer-cta mx-2" style="box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 15px;" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank" role="button">
                Download MDB
                <i class="fas fa-download ms-2"></i>
            </a>
            <a class="btn btn-outline-white footer-cta mx-2" style="box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 15px;" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">
                Start free tutorial
                <i class="fas fa-graduation-cap ms-2"></i>
            </a>
        </div>
        <!--/.Call to action-->

        <hr class="text-dark" />

        <div class="container">
            <!-- Section: Social media -->
            <section class="mb-3">
                <!-- Facebook -->
                <a class="btn-link btn-floating btn-lg text-white" href="#!" role="button" data-mdb-ripple-color="dark"><i class="fab fa-facebook-f"></i></a>

                <!-- Twitter -->
                <a class="btn-link btn-floating btn-lg text-white" href="#!" role="button" data-mdb-ripple-color="dark"><i class="fab fa-twitter"></i></a>

                <!-- Google -->
                <a class="btn-link btn-floating btn-lg text-white" href="#!" role="button" data-mdb-ripple-color="dark"><i class="fab fa-google"></i></a>

                <!-- Instagram -->
                <a class="btn-link btn-floating btn-lg text-white" href="#!" role="button" data-mdb-ripple-color="dark"><i class="fab fa-instagram"></i></a>

                <!-- YouTube -->
                <a class="btn-link btn-floating btn-lg text-white" href="#!" role="button" data-mdb-ripple-color="dark"><i class="fab fa-youtube"></i></a>
                <!-- Github -->
                <a class="btn-link btn-floating btn-lg text-white" href="#!" role="button" data-mdb-ripple-color="dark"><i class="fab fa-github"></i></a>
            </section>
            <!-- Section: Social media -->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); text-color: #e0e0e0;">
            © 2022 Copyright:
            <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
    </footer>

{% endblock content %}